/*
 *	machdep.h generated by machdep at Sun Jul 24 21:01:07 2016
 */

#ifndef __machdep_h__
#define __machdep_h__

#define MACH_SHORT_SIZE 2
#define MACH_INT_SIZE 4
#define MACH_LONG_SIZE 4
#define MACH_FLOAT_SIZE 4
#define MACH_DOUBLE_SIZE 8
#define MACH_BYTE_ORDER_LSB_FIRST
#define MACH_BITFIELDS_LSB_FIRST

#endif /* __machdep_h__ */
